task = 'Onomatopoeia'  
print(len(task))
print(task[0:2])
print(task[1:3])
print(task[3:6])
print(task[4:6])
print(task[5:8])
print(task.replace('top', 'bottom'))
print(task.upper())
print(task.lower())
print(task[-7:-4])
print(task[-9:-6])
print(task[-12:-10])
print(task[-8:-6])